enum IdiomDifficulty {
  easy,
  medium,
  hard,
}

class Idiom {
  final String idiom;
  final String pinyin; // 此處改為儲存注音
  final String meaning;
  final IdiomDifficulty difficulty;

  Idiom({
    required this.idiom,
    required this.pinyin,
    required this.meaning,
    required this.difficulty,
  });

  // 輔助方法：將注音音節拆分為基本注音和聲調
  Map<String, String> _splitZhuyinAndTone(String zhuyinSyllable) {
    final toneMarks = ['ˋ', 'ˊ', 'ˇ', '˙']; // 第四聲, 第二聲, 第三聲, 輕聲
    String baseZhuyin = zhuyinSyllable;
    String tone = '';

    if (zhuyinSyllable.isNotEmpty && toneMarks.contains(zhuyinSyllable[zhuyinSyllable.length - 1])) {
      tone = zhuyinSyllable[zhuyinSyllable.length - 1];
      baseZhuyin = zhuyinSyllable.substring(0, zhuyinSyllable.length - 1);
    }
    // 對於第一聲，tone 為空字串

    return {'base': baseZhuyin, 'tone': tone};
  }

  // 輔助方法：將成語字元與其注音配對
  // 假設 pinyin 字串的音節數量與 idiom 字串的字元數量相同
  List<Map<String, String>> getCharacterZhuyins() {
    List<String> zhuyinSyllables = pinyin.split(' ');
    List<Map<String, String>> charZhuyinPairs = [];

    if (idiom.length != zhuyinSyllables.length) {
      // 處理長度不匹配的情況，例如記錄錯誤或返回空列表
      // 為了簡化，這裡假設長度會匹配
      return [];
    }

    for (int i = 0; i < idiom.length; i++) {
      final splitResult = _splitZhuyinAndTone(zhuyinSyllables[i]);
      charZhuyinPairs.add({
        'char': idiom[i],
        'baseZhuyin': splitResult['base']!,
        'tone': splitResult['tone']!,
      });
    }
    return charZhuyinPairs;
  }
}

// 範例成語資料
final List<Idiom> sampleIdioms = [
  Idiom(
    idiom: '畫龍點睛',
    pinyin: 'ㄏㄨㄚˋ ㄌㄨㄥˊ ㄉㄧㄢˇ ㄐㄧㄥ',
    meaning: '比喻說話或文章在關鍵處加上精闢的語句，使內容生動有力。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '一心一意',
    pinyin: 'ㄧ ㄒㄧㄣ ㄧ ㄧˋ',
    meaning: '形容專心一志，毫不鬆懈。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '天花亂墜',
    pinyin: 'ㄊㄧㄢ ㄏㄨㄚ ㄌㄨㄢˋ ㄓㄨㄟˋ',
    meaning: '形容說話浮誇動聽，不切實際。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '三心二意',
    pinyin: 'ㄙㄢ ㄒㄧㄣ ㄦˋ ㄧˋ',
    meaning: '形容意志不堅定，猶豫不決。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '一鳴驚人',
    pinyin: 'ㄧ ㄇㄧㄥˊ ㄐㄧㄥ ㄖㄣˊ',
    meaning: '比喻平時沒有突出的表現，突然做出驚人的成績。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '守株待兔',
    pinyin: 'ㄕㄡˇ ㄓㄨ ㄉㄞˋ ㄊㄨˋ',
    meaning: '比喻拘泥守舊，不知變通，或存僥倖心理，企圖不勞而獲。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '井底之蛙',
    pinyin: 'ㄐㄧㄥˇ ㄉㄧˇ ㄓ ㄨㄚ',
    meaning: '比喻見識淺薄的人。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '自相矛盾',
    pinyin: 'ㄗˋ ㄒㄧㄤ ㄇㄠˊ ㄉㄨㄣˋ',
    meaning: '比喻說話或行事前後不一致。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '狐假虎威',
    pinyin: 'ㄏㄨˊ ㄐㄧㄚˇ ㄏㄨˇ ㄨㄟ',
    meaning: '比喻藉著有權者的威勢作威作福。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '杯弓蛇影',
    pinyin: 'ㄅㄟ ㄍㄨㄥ ㄕㄜˊ ㄧㄥˇ',
    meaning: '比喻疑神疑鬼，妄自驚擾。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '畫餅充飢',
    pinyin: 'ㄏㄨㄚˋ ㄅㄧㄥˇ ㄔㄨㄥ ㄐㄧ',
    meaning: '比喻用空想來安慰自己。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '緣木求魚',
    pinyin: 'ㄩㄢˊ ㄇㄨˋ ㄑㄧㄡˊ ㄩˊ',
    meaning: '爬到樹上去抓魚。比喻方向或方法不對，勞而無功。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '杞人憂天',
    pinyin: 'ㄑㄧˇ ㄖㄣˊ ㄧㄡ ㄊㄧㄢ',
    meaning: '比喻毫無意義或不必要的憂慮。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '驚弓之鳥',
    pinyin: 'ㄐㄧㄥ ㄍㄨㄥ ㄓ ㄋㄧㄠˇ',
    meaning: '比喻受過驚嚇的人，遇到一點動靜就非常害怕。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '愚公移山',
    pinyin: 'ㄩˊ ㄍㄨㄥ ㄧˊ ㄕㄢ',
    meaning: '比喻有恆心，有毅力，不怕困難。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '亡羊補牢',
    pinyin: 'ㄨㄤˊ ㄧㄤˊ ㄅㄨˇ ㄌㄠˊ',
    meaning: '比喻事情出了差錯，及時設法補救，以免再出問題。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '畫蛇添足',
    pinyin: 'ㄏㄨㄚˋ ㄕㄜˊ ㄊㄧㄢ ㄗㄨˊ',
    meaning: '比喻多此一舉，反而弄巧成拙。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '對牛彈琴',
    pinyin: 'ㄉㄨㄟˋ ㄋㄧㄡˊ ㄊㄢˊ ㄑㄧㄣˊ',
    meaning: '比喻對不懂道理的人講道理，白費力氣。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '聞雞起舞',
    pinyin: 'ㄨㄣˊ ㄐㄧ ㄑㄧˇ ㄨˇ',
    meaning: '比喻有高尚志向的人及時奮發努力。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '胸有成竹',
    pinyin: 'ㄒㄩㄥ ㄧㄡˇ ㄔㄥˊ ㄓㄨˊ',
    meaning: '比喻在做事前已經有了成熟的構思和完整的計畫。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '一字千金',
    pinyin: 'ㄧ ㄗˋ ㄑㄧㄢ ㄐㄧㄣ',
    meaning: '形容文章的詞句精妙，價值很高。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '塞翁失馬',
    pinyin: 'ㄙㄞˋ ㄨㄥ ㄕ ㄇㄚˇ',
    meaning: '比喻壞事可以變好，好事也可以變壞，禍福經常相互轉化。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '坐井觀天',
    pinyin: 'ㄗㄨㄛˋ ㄐㄧㄥˇ ㄍㄨㄢ ㄊㄧㄢ',
    meaning: '比喻眼界狹小，見識有限。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '風聲鶴唳',
    pinyin: 'ㄈㄥ ㄕㄥ ㄏㄜˋ ㄌㄧˋ',
    meaning: '比喻因疑神疑鬼而引起恐慌。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '刻舟求劍',
    pinyin: 'ㄎㄜˋ ㄓㄡ ㄑㄧㄡˊ ㄐㄧㄢˋ',
    meaning: '比喻人辦事不隨客觀情勢的變化而改變方法，思想保守。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '熟能生巧',
    pinyin: 'ㄕㄨˊ ㄋㄥˊ ㄕㄥ ㄑㄧㄠˇ',
    meaning: '指做事情熟練了，就能掌握技巧，做得更好。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '掩耳盜鈴',
    pinyin: 'ㄧㄢˇ ㄦˇ ㄉㄠˋ ㄌㄧㄥˊ',
    meaning: '比喻自己欺騙自己。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '邯鄲學步',
    pinyin: 'ㄏㄢˊ ㄉㄢ ㄒㄩㄝˊ ㄅㄨˋ',
    meaning: '比喻模仿別人不成，反而喪失自己原有的長處。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '紙上談兵',
    pinyin: 'ㄓˇ ㄕㄤˋ ㄊㄢˊ ㄅㄧㄥ',
    meaning: '比喻空談理論，不能解決實際問題。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '南轅北轍',
    pinyin: 'ㄋㄢˊ ㄩㄢˊ ㄅㄟˇ ㄓㄜˊ',
    meaning: '比喻行動和目的正好相反。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '拔苗助長',
    pinyin: 'ㄅㄚˊ ㄇㄧㄠˊ ㄓㄨˋ ㄓㄤˇ',
    meaning: '比喻違反事物發展的客觀規律，急於求成，反而把事情弄糟。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '鷸蚌相爭',
    pinyin: 'ㄩˋ ㄅㄤˋ ㄒㄧㄤ ㄓㄥ',
    meaning: '比喻雙方爭鬥，造成第三方獲利。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '九牛一毛',
    pinyin: 'ㄐㄧㄡˇ ㄋㄧㄡˊ ㄧ ㄇㄠˊ',
    meaning: '比喻極大數量中微不足道的一部分。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '程門立雪',
    pinyin: 'ㄔㄥˊ ㄇㄣˊ ㄌㄧˋ ㄒㄩㄝˇ',
    meaning: '比喻求學心切，專心致志。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '東施效顰',
    pinyin: 'ㄉㄨㄥ ㄕ ㄒㄧㄠˋ ㄆㄧㄣˊ',
    meaning: '比喻不顧本身條件，盲目模仿別人，結果適得其反。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '指鹿為馬',
    pinyin: 'ㄓˇ ㄌㄨˋ ㄨㄟˊ ㄇㄚˇ',
    meaning: '比喻故意顛倒黑白，混淆是非。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '雞鳴狗盜',
    pinyin: 'ㄐㄧ ㄇㄧㄥˊ ㄍㄡˇ ㄉㄠˋ',
    meaning: '比喻卑下卑微的技能，或比喻竊取他人勞動成果。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '懸梁刺股',
    pinyin: 'ㄒㄩㄢˊ ㄌㄧㄤˊ ㄘˋ ㄍㄨˇ',
    meaning: '形容專心刻苦，發奮讀書。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '破釜沉舟',
    pinyin: 'ㄆㄛˋ ㄈㄨˇ ㄔㄣˊ ㄓㄡ',
    meaning: '比喻下定決心，不顧一切地奮鬥到底。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '守口如瓶',
    pinyin: 'ㄕㄡˇ ㄎㄡˇ ㄖㄨˊ ㄆㄧㄥˊ',
    meaning: '形容說話謹慎，嚴守秘密。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '披星戴月',
    pinyin: 'ㄆㄧ ㄒㄧㄥ ㄉㄞˋ ㄩㄝˋ',
    meaning: '形容早出晚歸，旅途或工作極為辛苦。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '名列前茅',
    pinyin: 'ㄇㄧㄥˊ ㄌㄧㄝˋ ㄑㄧㄢˊ ㄇㄠˊ',
    meaning: '比喻成績優異，排在前面。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '曇花一現',
    pinyin: 'ㄊㄢˊ ㄏㄨㄚ ㄧ ㄒㄧㄢˋ',
    meaning: '比喻事物非常美好，卻很短暫地消失。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '半途而廢',
    pinyin: 'ㄅㄢˋ ㄊㄨˊ ㄦˊ ㄈㄟˋ',
    meaning: '比喻做事情沒恆心，進行到一半就停止。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '臥薪嘗膽',
    pinyin: 'ㄨㄛˋ ㄒㄧㄣ ㄔㄤˊ ㄉㄢˇ',
    meaning: '比喻刻苦自勵，發憤圖強，以達成目標。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '風調雨順',
    pinyin: 'ㄈㄥ ㄊㄧㄠˊ ㄩˇ ㄕㄨㄣˋ',
    meaning: '形容農作物發育所需的風雨及時適量，氣候宜人。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '錦上添花',
    pinyin: 'ㄐㄧㄣˇ ㄕㄤˋ ㄊㄧㄢ ㄏㄨㄚ',
    meaning: '比喻在原有的基礎上再增加好的事物。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '負荊請罪',
    pinyin: 'ㄈㄨˋ ㄐㄧㄥ ㄑㄧㄥˇ ㄗㄨㄟˋ',
    meaning: '表示向人誠懇認錯，請求原諒。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '草木皆兵',
    pinyin: 'ㄘㄠˇ ㄇㄨˋ ㄐㄧㄝ ㄅㄧㄥ',
    meaning: '形容驚恐到了極點，疑心極重。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '望梅止渴',
    pinyin: 'ㄨㄤˋ ㄇㄟˊ ㄓˇ ㄎㄜˇ',
    meaning: '比喻用幻想來寬慰自己，解決不了實際問題。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '水落石出',
    pinyin: 'ㄕㄨㄟˇ ㄌㄨㄛˋ ㄕˊ ㄔㄨ',
    meaning: '比喻事情真相大白。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '集思廣益',
    pinyin: 'ㄐㄧˊ ㄙ ㄍㄨㄤˇ ㄧˋ',
    meaning: '指集中眾人的智慧，能獲得更廣泛的效益。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '勢如破竹',
    pinyin: 'ㄕˋ ㄖㄨˊ ㄆㄛˋ ㄓㄨˊ',
    meaning: '比喻作戰或工作節節勝利，氣勢不可擋。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '滄海一粟',
    pinyin: 'ㄘㄤ ㄏㄞˇ ㄧ ㄙㄨˋ',
    meaning: '比喻渺小而微不足道。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '自強不息',
    pinyin: 'ㄗˋ ㄑㄧㄤˊ ㄅㄨˋ ㄒㄧˊ',
    meaning: '指自我努力向上，永不懈怠。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '望塵莫及',
    pinyin: 'ㄨㄤˋ ㄔㄣˊ ㄇㄛˋ ㄐㄧˊ',
    meaning: '形容遠遠落後，追趕不上。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '破鏡重圓',
    pinyin: 'ㄆㄛˋ ㄐㄧㄥˋ ㄔㄨㄥˊ ㄩㄢˊ',
    meaning: '比喻夫妻失散或決裂後重新團聚。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '投鼠忌器',
    pinyin: 'ㄊㄡˊ ㄕㄨˇ ㄐㄧˋ ㄑㄧˋ',
    meaning: '比喻做事有所顧忌，不敢放手去幹。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '脫穎而出',
    pinyin: 'ㄊㄨㄛ ㄧㄥˇ ㄦˊ ㄔㄨ',
    meaning: '比喻才華顯露，超越眾人。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '口若懸河',
    pinyin: 'ㄎㄡˇ ㄖㄨㄛˋ ㄒㄩㄢˊ ㄏㄜˊ',
    meaning: '形容人辯才無礙，說話流利。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '老馬識途',
    pinyin: 'ㄌㄠˇ ㄇㄚˇ ㄕˋ ㄊㄨˊ',
    meaning: '比喻有經驗的人對事情比較熟悉，能引導他人。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '拋磚引玉',
    pinyin: 'ㄆㄠ ㄓㄨㄢ ㄧㄣˇ ㄩˋ',
    meaning: '比喻先發表自己的淺見，以引出別人的高論。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '落花流水',
    pinyin: 'ㄌㄨㄛˋ ㄏㄨㄚ ㄌㄧㄡˊ ㄕㄨㄟˇ',
    meaning: '原形容春殘景色，後多比喻被打得慘敗。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '釜底抽薪',
    pinyin: 'ㄈㄨˇ ㄉㄧˇ ㄔㄡ ㄒㄧㄣ',
    meaning: '比喻從根本上解決問題。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '精忠報國',
    pinyin: 'ㄐㄧㄥ ㄓㄨㄥ ㄅㄠˋ ㄍㄨㄛˊ',
    meaning: '指對國家非常忠誠，竭盡全力報效。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '兩袖清風',
    pinyin: 'ㄌㄧㄤˇ ㄒㄧㄡˋ ㄑㄧㄥ ㄈㄥ',
    meaning: '比喻做官清廉。後也用來形容貧窮，一無所有。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '一箭雙鵰',
    pinyin: 'ㄧ ㄐㄧㄢˋ ㄕㄨㄤ ㄉㄧㄠ',
    meaning: '比喻做一件事可以同時達到兩個目標。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '東山再起',
    pinyin: 'ㄉㄨㄥ ㄕㄢ ㄗㄞˋ ㄑㄧˇ',
    meaning: '比喻失敗後重新振作，恢復原有的地位或氣勢。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '鳳毛麟角',
    pinyin: 'ㄈㄥˋ ㄇㄠˊ ㄌㄧㄣˊ ㄐㄧㄠˇ',
    meaning: '比喻稀罕珍貴的人或事物。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '破涕為笑',
    pinyin: 'ㄆㄛˋ ㄊㄧˋ ㄨㄟˊ ㄒㄧㄠˋ',
    meaning: '形容轉悲為喜，一下子停止哭泣，露出笑臉。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '望穿秋水',
    pinyin: 'ㄨㄤˋ ㄔㄨㄢ ㄑㄧㄡ ㄕㄨㄟˇ',
    meaning: '形容盼望得極其迫切。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '噤若寒蟬',
    pinyin: 'ㄐㄧㄣˋ ㄖㄨㄛˋ ㄏㄢˊ ㄔㄢˊ',
    meaning: '比喻受到威嚇後不敢說話。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '走馬看花',
    pinyin: 'ㄗㄡˇ ㄇㄚˇ ㄎㄢˋ ㄏㄨㄚ',
    meaning: '比喻觀察事物不深入，只是粗略地看過。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '墨守成規',
    pinyin: 'ㄇㄛˋ ㄕㄡˇ ㄔㄥˊ ㄍㄨㄟ',
    meaning: '形容思想保守，不肯改進創新，守著舊規矩不放。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '未雨綢繆',
    pinyin: 'ㄨㄟˋ ㄩˇ ㄔㄡˊ ㄇㄡˊ',
    meaning: '比喻事先做好準備，防患於未然。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '圖窮匕見',
    pinyin: 'ㄊㄨˊ ㄑㄩㄥˊ ㄅㄧˇ ㄒㄧㄢˋ',
    meaning: '比喻事情發展到最後，真相終於暴露出來。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '水滴石穿',
    pinyin: 'ㄕㄨㄟˇ ㄉㄧ ㄕˊ ㄔㄨㄢ',
    meaning: '比喻只要有恆心努力不懈，再難的事也能成功。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '班門弄斧',
    pinyin: 'ㄅㄢ ㄇㄣˊ ㄋㄨㄥˋ ㄈㄨˇ',
    meaning: '比喻在專家面前賣弄本事，不自量力。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '朝三暮四',
    pinyin: 'ㄓㄠ ㄙㄢ ㄇㄨˋ ㄙˋ',
    meaning: '比喻心意不定，反覆無常。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '明察秋毫',
    pinyin: 'ㄇㄧㄥˊ ㄔㄚˊ ㄑㄧㄡ ㄏㄠˊ',
    meaning: '形容目光敏銳，觀察入微，連極細小的地方也能看清楚。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '老生常談',
    pinyin: 'ㄌㄠˇ ㄕㄥ ㄔㄤˊ ㄊㄢˊ',
    meaning: '比喻聽慣了的無新意的舊話。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '口蜜腹劍',
    pinyin: 'ㄎㄡˇ ㄇㄧˋ ㄈㄨˋ ㄐㄧㄢˋ',
    meaning: '形容人嘴巴說得動聽，內心卻陰險狠毒。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '如魚得水',
    pinyin: 'ㄖㄨˊ ㄩˊ ㄉㄜˊ ㄕㄨㄟˇ',
    meaning: '比喻得到跟自己很投合的人或找到適合環境。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '釜中之魚',
    pinyin: 'ㄈㄨˇ ㄓㄨㄥ ㄓ ㄩˊ',
    meaning: '比喻處境極其危險，已近死亡。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '一視同仁',
    pinyin: 'ㄧ ㄕˋ ㄊㄨㄥˊ ㄖㄣˊ',
    meaning: '表示對人同樣看待，不分厚薄。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '煮豆燃萁',
    pinyin: 'ㄓㄨˇ ㄉㄡˋ ㄖㄢˊ ㄑㄧˊ',
    meaning: '比喻骨肉相殘。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '精益求精',
    pinyin: 'ㄐㄧㄥ ㄧˋ ㄑㄧㄡˊ ㄐㄧㄥ',
    meaning: '指好了還要求更好。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '三顧茅廬',
    pinyin: 'ㄙㄢ ㄍㄨˋ ㄇㄠˊ ㄌㄨˊ',
    meaning: '比喻誠心誠意地邀請他人。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '背道而馳',
    pinyin: 'ㄅㄟˋ ㄉㄠˋ ㄦˊ ㄔˊ',
    meaning: '比喻彼此的方向目標完全相反。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '安然無恙',
    pinyin: 'ㄢ ㄖㄢˊ ㄨˊ ㄧㄤˋ',
    meaning: '形容平安無事，沒有受損。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '胸無點墨',
    pinyin: 'ㄒㄩㄥ ㄨˊ ㄉㄧㄢˇ ㄇㄛˋ',
    meaning: '形容人沒有文化，學識淺薄。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '汗牛充棟',
    pinyin: 'ㄏㄢˋ ㄋㄧㄡˊ ㄔㄨㄥ ㄉㄨㄥˋ',
    meaning: '形容書籍極多。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '一鼓作氣',
    pinyin: 'ㄧ ㄍㄨˇ ㄗㄨㄛˋ ㄑㄧˋ',
    meaning: '比喻趁著氣勢正旺時，一口完成。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '大公無私',
    pinyin: 'ㄉㄚˋ ㄍㄨㄥ ㄨˊ ㄙ',
    meaning: '形容非常公平正直，沒有私心。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '草船借箭',
    pinyin: 'ㄘㄠˇ ㄔㄨㄢˊ ㄐㄧㄝˋ ㄐㄧㄢˋ',
    meaning: '比喻運用智慧，利用他人的力量來達成目的。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '每下愈況',
    pinyin: 'ㄇㄟˇ ㄒㄧㄚˋ ㄩˋ ㄎㄨㄤˋ',
    meaning: '比喻情況愈來愈壞。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '水到渠成',
    pinyin: 'ㄕㄨㄟˇ ㄉㄠˋ ㄑㄩˊ ㄔㄥˊ',
    meaning: '比喻條件成熟，事情自然成功。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '披肝瀝膽',
    pinyin: 'ㄆㄧ ㄍㄢ ㄌㄧˋ ㄉㄢˇ',
    meaning: '比喻坦誠相待，忠貞不二。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '巧取豪奪',
    pinyin: 'ㄑㄧㄠˇ ㄑㄩˇ ㄏㄠˊ ㄉㄨㄛˊ',
    meaning: '形容用不正當的手段奪取他人的財物。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '名實相符',
    pinyin: 'ㄇㄧㄥˊ ㄕˊ ㄒㄧㄤ ㄈㄨˊ',
    meaning: '名聲與實際表現相稱。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '如履薄冰',
    pinyin: 'ㄖㄨˊ ㄌㄩˇ ㄅㄛˊ ㄅㄧㄥ',
    meaning: '比喻行事極其謹慎小心。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '不勞而獲',
    pinyin: 'ㄅㄨˋ ㄌㄠˊ ㄦˊ ㄏㄨㄛˋ',
    meaning: '自己不勞動而佔有別人的勞動成果。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '別出心裁',
    pinyin: 'ㄅㄧㄝˊ ㄔㄨ ㄒㄧㄣ ㄘㄞˊ',
    meaning: '形容構思獨特，與眾不同。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '後起之秀',
    pinyin: 'ㄏㄡˋ ㄑㄧˇ ㄓ ㄒㄧㄡˋ',
    meaning: '稱讚後輩中表現優異的人才。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '舉一反三',
    pinyin: 'ㄐㄩˇ ㄧ ㄈㄢˇ ㄙㄢ',
    meaning: '形容人聰明，能從一件事推知其他的道理。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '一塵不染',
    pinyin: 'ㄧ ㄔㄣˊ ㄅㄨˋ ㄖㄢˇ',
    meaning: '形容非常清潔。也比喻人品高尚，不受世俗污染。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '前車之鑑',
    pinyin: 'ㄑㄧㄢˊ ㄔㄜ ㄓ ㄐㄧㄢˋ',
    meaning: '比喻先前的失敗經驗，可以作為後來的借鏡。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '罄竹難書',
    pinyin: 'ㄑㄧㄥˋ ㄓㄨˊ ㄋㄢˊ ㄕㄨ',
    meaning: '形容罪狀極多，多到寫不完。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '順水推舟',
    pinyin: 'ㄕㄨㄣˋ ㄕㄨㄟˇ ㄊㄨㄟ ㄓㄡ',
    meaning: '比喻順應趨勢辦事，或趁機行事。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '樂此不疲',
    pinyin: 'ㄌㄜˋ ㄘˇ ㄅㄨˋ ㄆㄧˊ',
    meaning: '指沉迷於某事，雖然辛苦卻不感到疲倦。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '揠苗助長',
    pinyin: 'ㄧㄚˋ ㄇㄧㄠˊ ㄓㄨˋ ㄓㄤˇ',
    meaning: '比喻急於求成，反而把事情弄糟。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '萬紫千紅',
    pinyin: 'ㄨㄢˋ ㄗˇ ㄑㄧㄢ ㄏㄨㄥˊ',
    meaning: '形容百花盛開，顏色繁多。也比喻事物豐富多彩。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '拋頭露面',
    pinyin: 'ㄆㄠ ㄊㄡˊ ㄌㄨˋ ㄇㄧㄢˋ',
    meaning: '指人在公開場合出現（舊時多指婦女）。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '豁然開朗',
    pinyin: 'ㄏㄨㄛˋ ㄖㄢˊ ㄎㄞ ㄌㄤˇ',
    meaning: '比喻突然領悟道理，或是眼界瞬間變得開闊。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '落井下石',
    pinyin: 'ㄌㄨㄛˋ ㄐㄧㄥˇ ㄒㄧㄚˋ ㄕˊ',
    meaning: '比喻乘人危難時加以陷害。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '瞠目結舌',
    pinyin: 'ㄔㄥ ㄇㄨˋ ㄐㄧㄝˊ ㄕㄜˊ',
    meaning: '形容受窘或驚呆到說不出話來的樣子。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '走投無路',
    pinyin: 'ㄗㄡˇ ㄊㄡˊ ㄨˊ ㄌㄨˋ',
    meaning: '形容處境極端困難，找不到出路。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '鎩羽而歸',
    pinyin: 'ㄕㄚ ㄩˇ ㄦˊ ㄍㄨㄟ',
    meaning: '比喻失意或失敗後，鬱鬱不樂地返回。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '入木三分',
    pinyin: 'ㄖㄨˋ ㄇㄨˋ ㄙㄢ ㄈㄣ',
    meaning: '原指書法力道強勁。後比喻評論深刻、描寫生動。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '目瞪口呆',
    pinyin: 'ㄇㄨˋ ㄉㄥˋ ㄎㄡˇ ㄉㄞ',
    meaning: '形容因驚嚇或驚異而發愣的樣子。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '負隅頑抗',
    pinyin: 'ㄈㄨˋ ㄩˊ ㄨㄢˊ ㄎㄤˋ',
    meaning: '比喻憑藉險要地勢，或在絕境中頑強抵抗。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '前功盡棄',
    pinyin: 'ㄑㄧㄢˊ ㄍㄨㄥ ㄐㄧㄣˋ ㄑㄧˋ',
    meaning: '指以前的努力完全白費。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '望其項背',
    pinyin: 'ㄨㄤˋ ㄑㄧˊ ㄒㄧㄤˋ ㄅㄟˋ',
    meaning: '表示趕得上。多用於否定句（望塵莫及的相反）。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '推陳出新',
    pinyin: 'ㄊㄨㄟ ㄔㄣˊ ㄔㄨ ㄒㄧㄣ',
    meaning: '排除舊有的，創造出新的事物。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '孤注一擲',
    pinyin: 'ㄍㄨ ㄓㄨˋ ㄧ ㄓˊ',
    meaning: '比喻危急時投入全部力量，冒險作最後一搏。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '良藥苦口',
    pinyin: 'ㄌㄧㄤˊ ㄧㄠˋ ㄎㄨˇ ㄎㄡˇ',
    meaning: '比喻真誠的勸告聽起來不舒服，但對人有益。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '螳臂當車',
    pinyin: 'ㄊㄤˊ ㄅㄧˋ ㄉㄤ ㄔㄜ',
    meaning: '比喻自不量力，終將失敗。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '小題大作',
    pinyin: 'ㄒㄧㄠˇ ㄊㄧˊ ㄉㄚˋ ㄗㄨㄛˋ',
    meaning: '比喻把小事當作大事來處理。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '夜長夢多',
    pinyin: 'ㄧㄝˋ ㄔㄤˊ ㄇㄥˋ ㄉㄨㄛ',
    meaning: '比喻時間拖久了，可能發生意外的變化。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '鐵證如山',
    pinyin: 'ㄊㄧㄝˇ ㄓㄥˋ ㄖㄨˊ ㄕㄢ',
    meaning: '形容證據確鑿，無法推翻。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '水木清華',
    pinyin: 'ㄕㄨㄟˇ ㄇㄨˋ ㄑㄧㄥ ㄏㄨㄚ',
    meaning: '形容風景優美，山水與草木交相輝映，景色清幽。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '得心應手',
    pinyin: 'ㄉㄜˊ ㄒㄧㄣ ㄧㄥˋ ㄕㄡˇ',
    meaning: '形容做事熟練，心手相應，運用自如。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '世外桃源',
    pinyin: 'ㄕˋ ㄨㄞˋ ㄊㄠˊ ㄩㄢˊ',
    meaning: '比喻風景優美、遠離塵囂且安樂祥和的世界。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '懸崖勒馬',
    pinyin: 'ㄒㄩㄢˊ ㄧㄞˊ ㄌㄜˋ ㄇㄚˇ',
    meaning: '比喻到了危險的邊緣及時悔悟，停止行動。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '舉足輕重',
    pinyin: 'ㄐㄩˇ ㄗㄨˊ ㄑㄧㄥ ㄓㄨㄥˋ',
    meaning: '指處於重要地位，一舉一動都會影響全域。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '雪中送炭',
    pinyin: 'ㄒㄩㄝˇ ㄓㄨㄥ ㄙㄨㄥˋ ㄊㄢˋ',
    meaning: '比喻在他人急需救援時給予物質或精神上的支持。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '陽奉陰違',
    pinyin: 'ㄧㄤˊ ㄈㄥˋ ㄧㄣ ㄨㄟˊ',
    meaning: '表面上恭敬服從，暗地裡卻違背命令。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '金蟬脫殼',
    pinyin: 'ㄐㄧㄣ ㄔㄢˊ ㄊㄨㄛ ㄑㄧㄠˋ',
    meaning: '比喻用計脫身，只留下空殼蒙蔽對手。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '名垂青史',
    pinyin: 'ㄇㄧㄥˊ ㄔㄨㄟˊ ㄑㄧㄥ ㄕˇ',
    meaning: '指偉大的功績或名聲永遠載於史冊。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '口是心非',
    pinyin: 'ㄎㄡˇ ㄕˋ ㄒㄧㄣ ㄈㄟ',
    meaning: '指說的話和心裡想的不一致。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '海市蜃樓',
    pinyin: 'ㄏㄞˇ ㄕˋ ㄕㄣˋ ㄌㄡˊ',
    meaning: '原指大氣折射產生的幻影，後比喻虛幻虛無、不存在的事物。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '草長鶯飛',
    pinyin: 'ㄘㄠˇ ㄓㄤˇ ㄧㄥ ㄈㄟ',
    meaning: '形容生機勃勃的春天景色。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '如虎添翼',
    pinyin: 'ㄖㄨˊ ㄏㄨˇ ㄊㄧㄢ ㄧˋ',
    meaning: '比喻強大者又增添了新的力量，變得更加強大。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '前仆後繼',
    pinyin: 'ㄑㄧㄢˊ ㄆㄨ ㄏㄡˋ ㄐㄧˋ',
    meaning: '形容奮勇向前，前一人倒下，後一人緊跟著上。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '不恥下問',
    pinyin: 'ㄅㄨˋ ㄔˇ ㄒㄧㄚˋ ㄨㄣˋ',
    meaning: '向地位低或學問不如自己的人請教而不感到羞恥。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '斗轉星移',
    pinyin: 'ㄉㄡˇ ㄓㄨㄢˇ ㄒㄧㄥ ㄧˊ',
    meaning: '形容時間的流逝，時序的更替。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '落花有意',
    pinyin: 'ㄌㄨㄛˋ ㄏㄨㄚ ㄧㄡˇ ㄧˋ',
    meaning: '比喻單方面的一廂情願。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '一葉知秋',
    pinyin: 'ㄧ ㄧㄝˋ ㄓ ㄑㄧㄡ',
    meaning: '比喻由細微的徵兆，可推知事物的發展趨勢或結果。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '滄海桑田',
    pinyin: 'ㄘㄤ ㄏㄞˇ ㄙㄤ ㄊㄧㄢ',
    meaning: '比喻世事變化巨大。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '杯水車薪',
    pinyin: 'ㄅㄟ ㄕㄨㄟˇ ㄔㄜ ㄒㄧㄣ',
    meaning: '比喻力量太小，無濟於事。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '隨遇而安',
    pinyin: 'ㄙㄨㄟˊ ㄩˋ ㄦˊ ㄢ',
    meaning: '指能適應各種環境，並感到滿足。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '集腋成裘',
    pinyin: 'ㄐㄧˊ ㄧㄝˋ ㄔㄥˊ ㄑㄧㄡˊ',
    meaning: '比喻積少成多。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '忍辱負重',
    pinyin: 'ㄖㄣˇ ㄖㄨˇ ㄈㄨˋ ㄓㄨㄥˋ',
    meaning: '為了完成艱巨的任務而忍受屈辱。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '空中樓閣',
    pinyin: 'ㄎㄨㄥ ㄓㄨㄥ ㄌㄡˊ ㄍㄜˊ',
    meaning: '比喻虛幻、沒有根據的事物。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '江郎才盡',
    pinyin: 'ㄐㄧㄤ ㄌㄤˊ ㄘㄞˊ ㄐㄧㄣˋ',
    meaning: '比喻文思枯竭，才華耗盡。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '不期而遇',
    pinyin: 'ㄅㄨˋ ㄑㄧˊ ㄦˊ ㄩˋ',
    meaning: '沒有約定而意外相遇。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '鵬程萬里',
    pinyin: 'ㄆㄥˊ ㄔㄥˊ ㄨㄢˋ ㄌㄧˇ',
    meaning: '比喻前程遠大，不可限量。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '風起雲湧',
    pinyin: 'ㄈㄥ ㄑㄧˇ ㄩㄣˊ ㄩㄥˇ',
    meaning: '形容事物發展迅速，聲勢浩大。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '同舟共濟',
    pinyin: 'ㄊㄨㄥˊ ㄓㄡ ㄍㄨㄥˋ ㄐㄧˋ',
    meaning: '比喻在困難的環境中，彼此團結互助，共同戰勝困難。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '百折不撓',
    pinyin: 'ㄅㄞˇ ㄓㄜˊ ㄅㄨˋ ㄋㄠˊ',
    meaning: '形容意志剛強，雖受盡挫折，仍不屈服。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '日新月異',
    pinyin: 'ㄖˋ ㄒㄧㄣ ㄩㄝˋ ㄧˋ',
    meaning: '形容發展進步得很快，不斷出現新事物、新氣象。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '力不從心',
    pinyin: 'ㄌㄧˋ ㄅㄨˋ ㄘㄨㄥˊ ㄒㄧㄣ',
    meaning: '心裡想做，但力量不夠，不能如願。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '大刀闊斧',
    pinyin: 'ㄉㄚˋ ㄉㄠ ㄎㄨㄛˋ ㄈㄨˇ',
    meaning: '比喻辦事果斷而有魄力。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '千鈞一髮',
    pinyin: 'ㄑㄧㄢ ㄐㄩㄣ ㄧ ㄈㄚˇ',
    meaning: '比喻情況極為危急。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '不苟言笑',
    pinyin: 'ㄅㄨˋ ㄍㄡˇ ㄧㄢˊ ㄒㄧㄠˋ',
    meaning: '形容態度莊重嚴肅，不隨便說笑。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '未卜先知',
    pinyin: 'ㄨㄟˋ ㄅㄨˇ ㄒㄧㄢ ㄓ',
    meaning: '比喻有預見能力。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '有的放矢',
    pinyin: 'ㄧㄡˇ ㄉㄧˋ ㄈㄤˋ ㄕˇ',
    meaning: '比喻說話做事有針對性。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '老謀深算',
    pinyin: 'ㄌㄠˇ ㄇㄡˊ ㄕㄣ ㄙㄨㄢˋ',
    meaning: '形容人辦事精明老練，計畫周密。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '光怪陸離',
    pinyin: 'ㄍㄨㄤ ㄍㄨㄞˋ ㄌㄨˋ ㄌㄧˊ',
    meaning: '形容現象奇異、色彩繁雜。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '耳濡目染',
    pinyin: 'ㄦˇ ㄖㄨˊ ㄇㄨˋ ㄖㄢˇ',
    meaning: '形容見得多聽得多了，無形中受到影響。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '自以為是',
    pinyin: 'ㄗˋ ㄧˇ ㄨㄟˊ ㄕˋ',
    meaning: '總以為自己是對的，形容主觀、不虛心。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '別開生面',
    pinyin: 'ㄅㄧㄝˊ ㄎㄞ ㄕㄥ ㄇㄧㄢˋ',
    meaning: '比喻另外開創一種新的局面或風格。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '投其所好',
    pinyin: 'ㄊㄡˊ ㄑㄧˊ ㄙㄨㄛˇ ㄏㄠˋ',
    meaning: '迎合對方的愛好。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '孤芳自賞',
    pinyin: 'ㄍㄨ ㄈㄤ ㄗˋ ㄕㄤˇ',
    meaning: '比喻自命清高，自我欣賞。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '盲人摸象',
    pinyin: 'ㄇㄤˊ ㄖㄣˊ ㄇㄛ ㄒㄧㄤˋ',
    meaning: '比喻看問題不全面，以偏概全。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '直言不諱',
    pinyin: 'ㄓˊ ㄧㄢˊ ㄅㄨˋ ㄏㄨㄟˋ',
    meaning: '直截了當地說出來，沒有什麼忌諱。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '按部就班',
    pinyin: 'ㄢˋ ㄅㄨˋ ㄐㄧㄡˋ ㄅㄢ',
    meaning: '指按照一定的條理、步驟辦事。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '挺身而出',
    pinyin: 'ㄊㄧㄥˇ ㄕㄣ ㄦˊ ㄔㄨ',
    meaning: '形容遇到危難或緊要關頭，勇敢地站出來。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '無微不至',
    pinyin: 'ㄨˊ ㄨㄟˊ ㄅㄨˋ ㄓˋ',
    meaning: '形容關懷、照顧得非常細心周到。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '量力而為',
    pinyin: 'ㄌㄧㄤˋ ㄌㄧˋ ㄦˊ ㄨㄟˊ',
    meaning: '按照自己的力量去辦事。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '開門見山',
    pinyin: 'ㄎㄞ ㄇㄣˊ ㄐㄧㄢˋ ㄕㄢ',
    meaning: '比喻說話或寫文章直截了當，一開始就進入主題。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '雷厲風行',
    pinyin: 'ㄌㄟˊ ㄌㄧˋ ㄈㄥ ㄒㄧㄥˊ',
    meaning: '比喻執行政策或命令嚴格而迅速。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '實事求是',
    pinyin: 'ㄕˊ ㄕˋ ㄑㄧㄡˊ ㄕˋ',
    meaning: '指從實際情況出發，正確地處理和解決問題。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '精疲力盡',
    pinyin: 'ㄐㄧㄥ ㄆㄧˊ ㄌㄧˋ ㄐㄧㄣˋ',
    meaning: '形容精神和體力都已經耗盡，極度疲勞。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '莫名其妙',
    pinyin: 'ㄇㄛˋ ㄇㄧㄥˊ ㄑㄧˊ ㄇㄧㄠˋ',
    meaning: '形容事情奇怪，讓人無法理解。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '語重心長',
    pinyin: 'ㄩˇ ㄓㄨㄥˋ ㄒㄧㄣ ㄔㄤˊ',
    meaning: '言辭誠懇，情意深長。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '循序漸進',
    pinyin: 'ㄒㄩㄣˊ ㄒㄩˋ ㄐㄧㄢˋ ㄐㄧㄣˋ',
    meaning: '按照一定的次序，逐步前進或發展。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '萬無一失',
    pinyin: 'ㄨㄢˋ ㄨˊ ㄧ ㄕ',
    meaning: '形容非常有把握，絕對不會出差錯。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '意氣風發',
    pinyin: 'ㄧˋ ㄑㄧˋ ㄈㄥ ㄈㄚ',
    meaning: '形容精神振奮，氣概昂揚。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '舉世矚目',
    pinyin: 'ㄐㄩˇ ㄕˋ ㄓㄨˇ ㄇㄨˋ',
    meaning: '全世界的人都在注視著。形容影響極大。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '異軍突起',
    pinyin: 'ㄧˋ ㄐㄩㄣ ㄊㄨˊ ㄑㄧˇ',
    meaning: '比喻一支新力量突然興起。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '得寸進尺',
    pinyin: 'ㄉㄜˊ ㄘㄨㄣˋ ㄐㄧㄣˋ ㄔˇ',
    meaning: '比喻貪得無厭，得到一點好處還想要更多。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '心安理得',
    pinyin: 'ㄒㄧㄣ ㄢ ㄌㄧˇ ㄉㄜˊ',
    meaning: '自以為做的事合乎道理，心裡很坦然。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '見仁見智',
    pinyin: 'ㄐㄧㄢˋ ㄖㄣˊ ㄐㄧㄢˋ ㄓˋ',
    meaning: '指對同一個問題，不同的人有不同的看法。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '各抒己見',
    pinyin: 'ㄍㄜˋ ㄕㄨ ㄐㄧˇ ㄐㄧㄢˋ',
    meaning: '各自發表自己的意見。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '名不虛傳',
    pinyin: 'ㄇㄧㄥˊ ㄅㄨˋ ㄒㄩ ㄔㄨㄢˊ',
    meaning: '名聲確實很好，不是虛假傳聞。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '因地制宜',
    pinyin: 'ㄧㄣ ㄉㄧˋ ㄓˋ ㄧˊ',
    meaning: '根據當地的實際情況，制定合適的措施。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '如願以償',
    pinyin: 'ㄖㄨˊ ㄩㄢˋ ㄧˇ ㄔㄤˊ',
    meaning: '願望得到了實現。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '自食其果',
    pinyin: 'ㄗˋ ㄕˊ ㄑㄧˊ ㄍㄨㄛˇ',
    meaning: '自己做了壞事，自己承擔不好的後果。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '言之有理',
    pinyin: 'ㄧㄢˊ ㄓ ㄧㄡˇ ㄌㄧˇ',
    meaning: '說的話很有道理。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '事半功倍',
    pinyin: 'ㄕˋ ㄅㄢˋ ㄍㄨㄥ ㄅㄟˋ',
    meaning: '形容費力小而收效大。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '呼之欲出',
    pinyin: 'ㄏㄨ ㄓ ㄩˋ ㄔㄨ',
    meaning: '形容畫像非常逼真，或文字描述得非常生動。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '夜以繼日',
    pinyin: 'ㄧㄝˋ ㄧˇ ㄐㄧˋ ㄖˋ',
    meaning: '形容日夜不停地工作或學習。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '知足常樂',
    pinyin: 'ㄓ ㄗㄨˊ ㄔㄤˊ ㄌㄜˋ',
    meaning: '指人如果知道滿足，心裡就會感到快樂。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '前所未有',
    pinyin: 'ㄑㄧㄢˊ ㄙㄨㄛˇ ㄨㄟˋ ㄧㄡˇ',
    meaning: '從來沒有過。形容事物新奇、重大。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '苦盡甘來',
    pinyin: 'ㄎㄨˇ ㄐㄧㄣˋ ㄍㄢ ㄌㄞˊ',
    meaning: '艱難困苦的日子過完了，美好的日子到來了。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '乘勝追擊',
    pinyin: 'ㄔㄥˊ ㄕㄥˋ ㄓㄨㄟ ㄐㄧˊ',
    meaning: '趁著勝利的形勢，繼續追趕打擊敵人或對手。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '深思熟慮',
    pinyin: 'ㄕㄣ ㄙ ㄕㄨˊ ㄌㄩˋ',
    meaning: '反覆深入地思考。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '無懈可擊',
    pinyin: 'ㄨˊ ㄒㄧㄝˋ ㄎㄜˇ ㄐㄧˊ',
    meaning: '形容非常嚴密，沒有任何漏洞可供攻擊。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '微不足道',
    pinyin: 'ㄨㄟ ㄅㄨˋ ㄗㄨˊ ㄉㄠˋ',
    meaning: '非常微小，不值得一提。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '聚精會神',
    pinyin: 'ㄐㄩˋ ㄐㄧㄥ ㄏㄨㄟˋ ㄕㄣˊ',
    meaning: '集中注意力，非常專心。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '滿載而歸',
    pinyin: 'ㄇㄢˇ ㄗㄞˋ ㄦˊ ㄍㄨㄟ',
    meaning: '裝滿了東西回來。比喻收穫很大。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '據理力爭',
    pinyin: 'ㄐㄩˋ ㄌㄧˇ ㄌㄧˋ ㄓㄥ',
    meaning: '依據道理，竭力爭論或爭取。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '應接不暇',
    pinyin: 'ㄧㄥˋ ㄐㄧㄝ ㄅㄨˋ ㄒㄧㄚˊ',
    meaning: '形容事物繁多，來不及接待或應付。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '鍥而不捨',
    pinyin: 'ㄑㄧㄝˋ ㄦˊ ㄅㄨˋ ㄕㄜˇ',
    meaning: '比喻做事持之以恆，堅持不懈。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '一帆風順',
    pinyin: 'ㄧ ㄈㄢˊ ㄈㄥ ㄕㄨㄣˋ',
    meaning: '比喻事情進展順利，沒有任何阻礙。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '十全十美',
    pinyin: 'ㄕˊ ㄑㄩㄢˊ ㄕˊ ㄇㄟˇ',
    meaning: '形容非常完美，毫無缺陷。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '九死一生',
    pinyin: 'ㄐㄧㄡˇ ㄙˇ ㄧ ㄕㄥ',
    meaning: '形容處境極其危險，好不容易才保住性命。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '八面玲瓏',
    pinyin: 'ㄅㄚ ㄇㄧㄢˋ ㄌㄧㄥˊ ㄌㄨㄥˊ',
    meaning: '形容人處世圓滑，各方面都能應付。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '七上八下',
    pinyin: 'ㄑㄧ ㄕㄤˋ ㄅㄚ ㄒㄧㄚˋ',
    meaning: '形容心情惶恐不安。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '六神無主',
    pinyin: 'ㄌㄧㄡˋ ㄕㄣˊ ㄨˊ ㄓㄨˇ',
    meaning: '形容驚慌失措，不知如何是好。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '五花八門',
    pinyin: 'ㄨˇ ㄏㄨㄚ ㄅㄚ ㄇㄣˊ',
    meaning: '比喻花樣繁多，變化多端。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '四海為家',
    pinyin: 'ㄙˋ ㄏㄞˇ ㄨㄟˊ ㄐㄧㄚ',
    meaning: '指志向遠大，不留戀故鄉。後形容居處不定，隨處生活。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '三生有幸',
    pinyin: 'ㄙㄢ ㄕㄥ ㄧㄡˇ ㄒㄧㄥˋ',
    meaning: '形容極其幸運。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '二話不說',
    pinyin: 'ㄦˋ ㄏㄨㄚˋ ㄅㄨˋ ㄕㄨㄛ',
    meaning: '指毫不猶豫，非常爽快。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '萬馬奔騰',
    pinyin: 'ㄨㄢˋ ㄇㄚˇ ㄅㄣ ㄊㄥˊ',
    meaning: '形容氣勢磅礴，場面壯觀。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '千變萬化',
    pinyin: 'ㄑㄧㄢ ㄅㄧㄢˋ ㄨㄢˋ ㄏㄨㄚˋ',
    meaning: '形容變化極多。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '百戰百勝',
    pinyin: 'ㄅㄞˇ ㄓㄢˋ ㄅㄞˇ ㄕㄥˋ',
    meaning: '每次戰鬥都能取得勝利。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '十拿九穩',
    pinyin: 'ㄕˊ ㄋㄚˊ ㄐㄧㄡˇ ㄨㄣˇ',
    meaning: '形容很有把握。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '一舉兩得',
    pinyin: 'ㄧ ㄐㄩˇ ㄌㄧㄤˇ ㄉㄜˊ',
    meaning: '做一件事同時獲得兩項好處。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '多此一舉',
    pinyin: 'ㄉㄨㄛ ㄘˇ ㄧ ㄐㄩˇ',
    meaning: '指做了多餘的事，反而不合適。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '左右逢源',
    pinyin: 'ㄗㄨㄛˇ ㄧㄡˋ ㄈㄥˊ ㄩㄢˊ',
    meaning: '比喻辦事得心應手，非常順利。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '前程似錦',
    pinyin: 'ㄑㄧㄢˊ ㄔㄥˊ ㄙˋ ㄐㄧㄣˇ',
    meaning: '形容前途非常美好。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '後會有期',
    pinyin: 'ㄏㄡˋ ㄏㄨㄟˋ ㄧㄡˇ ㄑㄧˊ',
    meaning: '表示以後還有見面的機會。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '心曠神怡',
    pinyin: 'ㄒㄧㄣ ㄎㄨㄤˋ ㄕㄣˊ ㄧˊ',
    meaning: '心情開朗，精神愉悅。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '欣欣向榮',
    pinyin: 'ㄒㄧㄣ ㄒㄧㄣ ㄒㄧㄤˋ ㄖㄨㄥˊ',
    meaning: '形容草木長得茂盛。後比喻事業繁榮興旺。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '朝氣蓬勃',
    pinyin: 'ㄓㄠ ㄑㄧˋ ㄆㄥˊ ㄅㄛˊ',
    meaning: '形容充滿活力，非常有精神。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '滿腔熱血',
    pinyin: 'ㄇㄢˇ ㄑㄧㄤ ㄖㄜˋ ㄒㄩㄝˇ',
    meaning: '形容充滿熱情和正義感。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '情不自禁',
    pinyin: 'ㄑㄧㄥˊ ㄅㄨˋ ㄗˋ ㄐㄧㄣ',
    meaning: '抑制不住自己的感情。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '脫胎換骨',
    pinyin: 'ㄊㄨㄛ ㄊㄞ ㄏㄨㄢˋ ㄍㄨˇ',
    meaning: '比喻徹底改變。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '捨己為人',
    pinyin: 'ㄕㄜˇ ㄐㄧˇ ㄨㄟˋ ㄖㄣˊ',
    meaning: '犧牲自己的利益去幫助他人。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '大獲全勝',
    pinyin: 'ㄉㄚˋ ㄏㄨㄛˋ ㄑㄩㄢˊ ㄕㄥˋ',
    meaning: '取得了全面的勝利。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '虛懷若谷',
    pinyin: 'ㄒㄩ ㄏㄨㄞˊ ㄖㄨㄛˋ ㄍㄨˇ',
    meaning: '形容為人非常謙虛。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '氣宇軒昂',
    pinyin: 'ㄑㄧˋ ㄩˇ ㄒㄩㄢ ㄤˊ',
    meaning: '形容人精神飽滿，氣概非凡。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '頂天立地',
    pinyin: 'ㄉㄧㄥˇ ㄊㄧㄢ ㄌㄧˋ ㄉㄧˋ',
    meaning: '形容人形象高大，氣概雄偉豪邁。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '暢所欲言',
    pinyin: 'ㄔㄤˋ ㄙㄨㄛˇ ㄩˋ ㄧㄢˊ',
    meaning: '痛痛快快地把心裡要說的話都說出來。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '侃侃而談',
    pinyin: 'ㄎㄢˇ ㄎㄢˇ ㄦˊ ㄊㄢˊ',
    meaning: '理直氣壯、從容不迫地說話。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '信口開河',
    pinyin: 'ㄒㄧㄣˋ ㄎㄡˇ ㄎㄞ ㄏㄜˊ',
    meaning: '比喻隨口亂說一氣。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '囫圇吞棗',
    pinyin: 'ㄏㄨˊ ㄌㄨㄣˊ ㄊㄨㄣ ㄗㄠˇ',
    meaning: '比喻理解事物籠統含糊，不加分析，不求甚解。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '按圖索驥',
    pinyin: 'ㄢˋ ㄊㄨˊ ㄙㄨㄛˇ ㄐㄧˋ',
    meaning: '比喻做事拘泥於教條，不知變通。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '夜郎自大',
    pinyin: 'ㄧㄝˋ ㄌㄤˊ ㄗˋ ㄉㄚˋ',
    meaning: '比喻人無知而又狂妄自大。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '對症下藥',
    pinyin: 'ㄉㄨㄟˋ ㄓㄥˋ ㄒㄧㄚˋ ㄧㄠˋ',
    meaning: '比喻針對具體情況決定解決問題的辦法。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '出類拔萃',
    pinyin: 'ㄔㄨ ㄌㄟˋ ㄅㄚˊ ㄘㄨㄟˋ',
    meaning: '形容品德、才能超出一般人。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '亦步亦趨',
    pinyin: 'ㄧˋ ㄅㄨˋ ㄧˋ ㄑㄩ',
    meaning: '比喻事事模仿或追隨別人。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '刻不容緩',
    pinyin: 'ㄎㄜˋ ㄅㄨˋ ㄖㄨㄥˊ ㄏㄨㄢˇ',
    meaning: '形容情勢緊迫，一刻也不允許拖延。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '義無反顧',
    pinyin: 'ㄧˋ ㄨˊ ㄈㄢˇ ㄍㄨˋ',
    meaning: '秉持正義勇往直前，絕不退縮。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '流連忘返',
    pinyin: 'ㄌㄧㄡˊ ㄌㄧㄢˊ ㄨㄤˋ ㄈㄢˇ',
    meaning: '形容留戀美景或某種事物，捨不得離開。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '高瞻遠矚',
    pinyin: 'ㄍㄠ ㄓㄢ ㄩㄢˇ ㄓㄨˇ',
    meaning: '形容眼光遠大。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '錙銖必較',
    pinyin: 'ㄗ ㄓㄨ ㄅㄧˋ ㄐㄧㄠˋ',
    meaning: '形容人非常小氣，或對極小的事也斤斤計較。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '防微杜漸',
    pinyin: 'ㄈㄤˊ ㄨㄟ ㄉㄨˋ ㄐㄧㄢˋ',
    meaning: '在錯誤或壞事剛萌芽時就加以制止，不讓它發展。',
    difficulty: IdiomDifficulty.hard,
  ),
  Idiom(
    idiom: '絡繹不絕',
    pinyin: 'ㄌㄨㄛˋ ㄧˋ ㄅㄨˋ ㄐㄩㄝˊ',
    meaning: '形容行人車馬來來往往，接連不斷。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '興高采烈',
    pinyin: 'ㄒㄧㄥˋ ㄍㄠ ㄘㄞˇ ㄌㄧㄝˋ',
    meaning: '形容興致很高，情緒熱烈。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '愛不釋手',
    pinyin: 'ㄞˋ ㄅㄨˋ ㄕˋ ㄕㄡˇ',
    meaning: '喜愛得捨不得放手。',
    difficulty: IdiomDifficulty.easy,
  ),
  Idiom(
    idiom: '層出不窮',
    pinyin: 'ㄘㄥˊ ㄔㄨ ㄅㄨˋ ㄑㄩㄥˊ',
    meaning: '接連不斷地出現，沒有窮盡。',
    difficulty: IdiomDifficulty.medium,
  ),
  Idiom(
    idiom: '嘆為觀止',
    pinyin: 'ㄊㄢˋ ㄨㄟˊ ㄍㄨㄢ ㄓˇ',
    meaning: '形容事物完美到了極點。',
    difficulty: IdiomDifficulty.medium,
  ),
];
